### ISSUE TITLE
Add cost in the language file

### ISSUE THREAD

**Issue by WongIong** [ZombieStriker/QualityArmoryVehicles2#74] opened 2021-12-08 00:28 UTC
Seems that vehicles still can be take out via gui shop.
it doesnt take the money but then still give you the vehicle.
in this case, no message will be shown if you have enough money or not.

**Comment by Lorenzo0111** [comment] 2021-12-08 11:45
Are you sure you that you are running Vault with an economy plugin?

**Comment by WongIong** [comment] 2021-12-08 13:55
Yes i do, QA is working fine

**Comment by Lorenzo0111** [comment] 2021-12-08 15:29
what economy plugin are you using?

**Comment by WongIong** [comment] 2021-12-08 17:00
EssentialX

**Comment by Lorenzo0111** [comment] 2021-12-08 17:08
ok

**Comment by Lorenzo0111** [comment] 2022-01-07 16:36
Still cannot reproduce

**Comment by WongIong** [comment] 2022-01-07 17:47
![image](https://user-images.githubusercontent.com/36799194/148585039-bd1c87c9-8c0b-41ce-8873-6f9704ef159f.png)
I don't know why can't you reproduce this.
With these plugins i still can get items from qav shop

**Comment by WongIong** [comment] 2022-01-07 17:49
actual essentials balance is 1000

**Comment by WongIong** [comment] 2022-01-07 17:50
i have deleted all file of these 5 installed plugins. still happens

**Comment by WongIong** [comment] 2022-01-07 17:55
I've also reinstalled it with the newest release from spigot page.

**Comment by Lorenzo0111** [comment] 2022-01-07 19:03
Can you try without QualityArmory installed?

**Comment by WongIong** [comment] 2022-01-07 21:25
without QA, it works again

**Comment by Lorenzo0111** [comment] 2022-01-08 07:41
ok, can you send your qa configuration?

**Comment by WongIong** [comment] 2022-01-08 17:30
https://pastebin.com/YGx7Rn8f

**Comment by Lorenzo0111** [comment] 2022-01-08 17:42
ok

**Comment by Lorenzo0111** [comment] 2022-01-09 07:41
Should be fixed with the latest version

**Comment by WongIong** [comment] 2022-01-09 16:47
ok, when will it be released?

**Comment by Lorenzo0111** [comment] 2022-01-09 16:56
it should already be released

**Comment by WongIong** [comment] 2022-01-09 18:01
Oh, yes it is fixed.
Thx!

**Comment by WongIong** [comment] 2022-01-09 18:13
Btw. the string "cost" has not yet in the lang file

**Closed** 2022-03-24 11:23 UTC
Labels: enhancement
